
using UnityEngine;

namespace fighting_game
{

    public class Playercon : MonoBehaviour
    {

        [SerializeField] public float power;
        [SerializeField] public float movespead;
        [SerializeField] private float jumpforce;
        [SerializeField] private float Gravity;

        public Transform atackpoint;
        public float atackradius;
        public LayerMask enemylayer;
        public Rigidbody2D rb;
        public Animator animator;
        public Collider2D[] hitenemys;
        public hp_sc _hp;
        private string colision = "yuka1";
        private bool _isground = false;

        void Start()
        {
            rb = GetComponent<Rigidbody2D>();
            animator = GetComponent<Animator>();
        }

        void Update()
        {
            //TODO æ•µã®æ–¹å‘ã«å¿…ãšå‘ãã‚ˆã†ã«ã—ãŸã„
            //TODO æ•µã«èƒŒã‚’å‘ã‘ãšã«å¾Œãšã•ã‚ŠãŸã„ã€€ãƒ¼ï¼animation?

            Movement(); //ç§»å‹•å‡¦ç†

            //ã‚¸ãƒ£ãƒ³ãƒ—å‡¦ç†
            if (_isground == true) Jump();
            //ç”»é¢å¤–ã«å‡ºãªã„ã‚ˆã†
            Adjust();

            //æ”»æ’ƒå‡¦ç†
            //ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼ã®ğŸ”³ãƒœã‚¿ãƒ³ã®å‡¦ç†
            if (Input.GetKey(KeyCode.U)) Atackmove();

        }

        /// <summary> /// ç§»å‹•é–¢æ•° /// </summary>
        private void Movement()
        {
            float x;
            x = Input.GetAxisRaw("Horizontal") / 1;//æ–¹å‘ã‚­ãƒ¼ï¼ˆæ¨ªï¼‰

            if (Mathf.Abs(x) < 0.1f)
            {
                x = 0f;
            }

            Debug.Log(x);
            if (x < 0)
            {
                transform.localScale = new Vector3(-1, 1, 1);
            }
            if (x > 0)
            {
                transform.localScale = new Vector3(1, 1, 1);
            }
            animator.SetFloat("Speed", Mathf.Abs(x));
            rb.velocity = new Vector2(x * movespead, rb.velocity.y);

        }
        /// <summary> /// ç”»é¢å¤–ã«å‡ºã•ãªã„ /// </summary>
        private void Adjust()
        {
            Vector3 pos = Camera.main.WorldToViewportPoint(transform.position);
            pos.x = (pos.x < 0f) ? 0 : (pos.x > 1f) ? 1 : pos.x;
            pos.y = (pos.y < 0f) ? 0 : (pos.y > 1f) ? 1 : pos.y;
            transform.position = Camera.main.ViewportToWorldPoint(pos);
        }

        /// <summary>/// æ”»æ’ƒé–¢æ•°ã€€/// </summary>
        private void Atackmove()
        {
            Debug.Log("æ”»æ’ƒã—ã¦ã„ã‚‹ã‚ˆ");
            animator.SetTrigger("atack");
            //å½“ãŸã‚Šåˆ¤å®šå‡¦ç†
            hitenemys = Physics2D.OverlapCircleAll(atackpoint.position, atackradius, enemylayer);
            foreach (Collider2D hitenemy in hitenemys)
            {
                Debug.Log(hitenemy.gameObject.name + "ã«æ”»æ’ƒ");
                hitenemy.GetComponent<Enemy>().ENEdame(power);
            }

        }
        //å½“ãŸã‚Šåˆ¤å®šã®å††ã«è‰²ã‚’ä»˜ã‘ã‚‹é–¢æ•°
        private void OnDrawGizmosSelected()
        {
            Gizmos.color = Color.red;
            Gizmos.DrawWireSphere(atackpoint.position, atackradius);
        }

        private void Jump()
        {
            float y;
            y = Input.GetAxis("Vertical");
            if (Mathf.Abs(y) < 0.1f)
            {
                y = 0f;
            }
            Debug.Log(y);
            animator.SetFloat("Jump", Mathf.Abs(y));
            if (y > 0)
            {
                rb.velocity = new Vector2(rb.velocity.x, y * jumpforce);
            }
            _isground = false;
        }

        public void OnCollisionEnter2D(Collision2D other)
        {
            Debug.Log("åœ°é¢ã«å½“ãŸã£ã¦ã„ã‚‹ã‚ˆ");
            if (_isground == false) { _isground = true; }
        }

        /// <summary>ã€€/// ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ãƒ€ãƒ¡ãƒ¼ã‚¸å‡¦ç†ã€€/// </summary>/// <param name="dmg"></param>
        public void Playerdame(float dmg)
        {
            animator.SetTrigger("dame");
            //_hp.curenthelth -= (int)dmg;
            _hp.UpdateplayhelthUI();
            //if (_hp.curenthelth <= 0)
            //{
            //    Debug.Log("Playerã®è² ã‘");
            //    Playerdead();
            //}
        }

        /// <summary>ã€€/// æ­»äº¡å‡¦ç†ã€€/// </summary>
        public void Playerdead()
        {
            //_hp.curenthelth = 0;
            //playerã®æ­»äº¡å‡¦ç†
            animator.SetBool("dead", true);
            Debug.Log("Playerdie");
        }


    }
}
